name: cd

on:
  workflow_dispatch:
  push:
    tags:
      - v-*

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name : Setup Amplify
        run: yarn global add @aws-amplify/cli
      - name: Restore cache
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: ./node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --non-interactive --production
      - name: Setup Amplify
        run: amplify pull --appId ${{ secrets.AMPLIFY_APP_ID }} --envName prod --yes
      - name: Amplify checkout
        run: amplify env checkout prod
      - name: Push
        run: amplify push --yes
      - name: Publish
        run: amplify publish --yes
